spring:
  application:
    name: api-best-practices-boot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cache:
    type: redis

# Custom properties for idempotency settings
idempotency:
  lock-expiration: 5 # In seconds
  cache-expiration: 3600 # 1 hour in seconds
