spring:
  application:
    name: api-best-practices-boot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        sort: amount,desc
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers  # Expose health, info, and loggers endpoints

  endpoint:
    health:
      show-details: always  # Always show detailed health information in the response

  health:
    probes:
      enabled: true  # Enable readiness and liveness probes

  simple:
    metrics:
      export:
        enabled: true

# Custom properties for idempotency settings
idempotency:
  lock-expiration: 5 # In seconds
  cache-expiration: 3600 # 1 hour in seconds
