spring:
  application:
    name: api-best-practices-boot
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cache:
    type: redis

# Custom properties for idempotency settings
idempotency:
  lock-expiration: 5 # In seconds
  cache-expiration: 3600 # 1 hour in seconds
