{
 "title": "API Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, uri))",
     "legendFormat": "Latency 99th Percentile"
    }
   ]
  },
  {
   "title": "Request Rate (per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "Requests Rate"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, uri))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Request Errors (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[5m])) by (uri)",
     "legendFormat": "4xx Errors"
    }
   ]
  },
  {
   "title": "Request Errors (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{status=~\"5..\"}[5m])) by (uri)",
     "legendFormat": "5xx Errors"
    }
   ]
  },
  {
   "title": "Request Duration (Median)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, uri))",
     "legendFormat": "50th Percentile (Median)"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(http_server_requests_active_seconds_gcount) by (uri)"
    }
   ]
  },
  {
   "title": "Max Request Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max) by (uri)"
    }
   ]
  },
  {
   "title": "Min Request Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "min(http_server_requests_seconds_max) by (uri)"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total{status=~\"2..\"}[5m])) by (uri)"
    }
   ]
  },
  {
   "title": "Request Count by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total[5m])) by (status)"
    }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total[5m])) by (uri)"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 120 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "JVM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 130 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 140 },
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 150 },
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 160 },
   "targets": [
    { "expr": "jdbc_connections_idle" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 170 },
   "targets": [
    { "expr": "jdbc_connections_active" }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "sum(rate(spring_data_repository_invocations_seconds_sum[1m])) by (repository)"
    }
   ]
  },
  {
   "title": "Cache Hits and Misses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total[5m])) by (result)"
    }
   ]
  }
 ]
}