
services:
  # Resources Section (Redis)
  redis-master:
    image: redis:6.2
    container_name: redis-master
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_PASSWORD=yourpassword

  redis-sentinel:
    image: redis:6.2
    container_name: redis-sentinel
    command: [ "redis-sentinel", "/usr/local/etc/redis/sentinel.conf" ]
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  redis-master-data:
  redis-slave-data:
